
name: cargo

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Protobuf compiler
              uses: arduino/setup-protoc@v1
              with:
                  version: 3.x
            - name: Install sccache
              run: curl --output sccache.tar.gz --location https://github.com/mozilla/sccache/releases/download/v0.3.1/sccache-dist-v0.3.1-x86_64-unknown-linux-musl.tar.gz && tar -xvf sccache.tar.gz && cp sccache-dist-v0.3.1-x86_64-unknown-linux-musl/sccache-dist /usr/local/bin/sccache && chmod u+x /usr/local/bin/sccache
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
            - name: Configure sccache
              uses: actions/github-script@v6
              with:
                  script: |
                      core.exportVariable("ACTIONS_CACHE_URL", process.env.ACTIONS_CACHE_URL || "");
                      core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env.ACTIONS_RUNTIME_TOKEN || "''");
            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --all-features
              env:
                  SCCACHE_GHA_CACHE_FROM: sccache-rs-
                  SCCACHE_GHA_CACHE_TO: sccache-rs-${{ env.GITHUB_SHA }}
            - uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --release --all-features